### ISSUE TITLE
capital problems

### ISSUE THREAD

**Issue by Rosalie241** [Plazmaz/Duckuino#1]
can you make it that it does not search for like GUI when you type gui(small letters)?

**Comment by Plazmaz** [comment]
So to ensure I'm understanding you correctly, lowercase "gui" is interpreted as a keypress of the GUI key, right?

**Comment by Rosalie241** [comment]
It does not do that yet I want to have that.

Verzonden vanaf Samsung Mobile.

-------- Oorspronkelijk bericht --------
Van: Dylan Katz notifications@github.com 
Datum: 23-06-2016  21:59  (GMT+01:00) 
Aan: Plazmaz/Duckuino Duckuino@noreply.github.com 
CC: tim241 Tim241@ziggo.nl, Author author@noreply.github.com 
Onderwerp: Re: [Plazmaz/Duckuino] capital problems (#1) 

So to ensure I'm understanding you correctly, lowercase "gui" is interpreted as a keypress of the GUI key? —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by Plazmaz** [comment]
@tim241 should be resolved

**Comment by Rosalie241** [comment]
You did not fixed it, now you capitalize everything. I am working on a converter too. You need to check for the beginning of the line and if one of the commands are true it needs to capitalizize it. I tried the same and I am working on it.

**Comment by Plazmaz** [comment]
Will revert my lazy fix.
